name: myapp
description: Flutter app for Azert reporting.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # Stable version range

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_auth_web: ^5.14.2
  cloud_firestore: ^5.6.7
  provider: ^6.0.5
  flutter_form_builder: ^10.0.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
